# --------------------------------------------------------------------------
# Sample project on_off
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=on_off
ARCH=pic14

include ptc_rules.inc

# --------------------------------------------------------------------------
