# --------------------------------------------------------------------------
# Sample project blink_led_tmr0
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
#
# --------------------------------------------------------------------------

PROJECT=blink_led_tmr0
MODEL=12f675
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------
