# --------------------------------------------------------------------------
# Sample project blink_led_tmr0
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
#
# --------------------------------------------------------------------------

PROJECT=blink_led_tmr0
ARCH=pic14

PIN_LED=5
SDCC_ARGS=-DPIN_LED=$(PIN_LED)

include ../rules.inc

# --------------------------------------------------------------------------
