// --------------------------------------------------------------------------
// pic-toolchain: autoconfigure C-code for PIC16F1829
//
// Note: this file is included from picconfig.h, which in turn is automatically
//       generated by the makefile (see ptc_rules.inc)
//
// Author: Bernhard Bablok
//
// https://github.com/bablokb/pic-toolchain
//
// --------------------------------------------------------------------------

#ifndef PICCONFIG_16F1829_H
  #define PICCONFIG_16F1829_H

  #include "picconfig_default.h"

  // IOC-macros
  #define IOC_ENABLE(pin,port,edge) \
    if (edge & IOC_POS_EDGE) { \
      bitset(IOC##port##P,pin); \
    } \
    if (edge & IOC_NEG_EDGE) { \
      bitset(IOC##port##N,pin); \
  }
  #define IOC_CLEAR(pin,port) \
    bitclear(IOC##port##F,pin);

  #ifdef __SDCC
    #define __16F1829
    // special initialization (empty)
    #define INIT_SPECIAL

    #define CONFIG_WORDS \
      __code uint16_t __at (_CONFIG1) __configword1 = \
        MCLR & _PWRTE_ON & _WDTE_OFF & _CLKOUTEN_OFF & _BOREN_OFF & _FOSC_INTOSC; \
      __code uint16_t __at (_CONFIG2) __configword2 = _LVP_OFF & _DEBUG_OFF

    #ifndef NOT_GPPU
      #define NOT_GPPU NOT_WPUEN
    #endif
    #ifndef nWPUEN
      #define nWPUEN   NOT_WPUEN
    #endif

  #elif defined __XC8
    #pragma config MCLRE = MCLR, PWRTE = ON, WDTE = OFF, FOSC = INTOSC
    #pragma config CLKOUTEN = OFF, BOREN = OFF, LVP = OFF

    #ifndef NOT_GPPU
      #define NOT_GPPU nWPUEN
    #endif
    #ifndef NOT_WPUEN
      #define NOT_WPUEN nWPUEN
    #endif

  #endif

  // run at 4MHz
  #define CLOCK_4MHZ \
      OSCCONbits.IRCF = 0b1101;                 // run at 4MHz

#endif
