// --------------------------------------------------------------------------
// pic-toolchain: autoconfigure C-code for PIC12F675
//
// Note: this file is included from picconfig.h, which in turn is automatically
//       generated by the makefile (see rules.inc)
//
// Author: Bernhard Bablok
//
// https://github.com/bablokb/pic-toolchain
//
// --------------------------------------------------------------------------

#ifndef PICCONFIG_12F675_H
  #define PICCONFIG_12F675_H

  #ifdef __SDCC
    #include <pic14regs.h>
    #include "picconfig_default.h"

    // special initialization
    #undef RP0
    #define INIT_SPECIAL \
      __asm \
        bsf  STATUS, RP0 \
        call 0x3ff    ; Wert auslesen \
        movwf OSCCAL  ; Wert setzen \
        bcf  STATUS, RP0 \
      __endasm;

    // run at 4MHz (empty, since it is the default)
    #define CLOCK_4MHZ

    #define CONFIG_WORDS \
      __code uint16_t __at (_CONFIG) __configword = \
        MCLR & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT & _BODEN_OFF;
  #endif
#endif
