# --------------------------------------------------------------------------
# Sample project uart_tx
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=uart_tx
EXTRA_C=softuart.c
EXTRA_ASM=delay.asm quarz4MHz.asm
MODEL=12f675
ARCH=pic14

include ptc_rules.inc

# --------------------------------------------------------------------------
