# --------------------------------------------------------------------------
# Sample project rpi_mosfet_on_off
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=rpi_mosfet_on_off
EXTRA_ASM=quarz4MHz.asm
MODEL=12f675
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------
