# --------------------------------------------------------------------------
# Sample project blink_led_quarz4MHz
#
# Call external ASM-routine
# See https://sourceforge.net/p/sdcc/mailman/message/35239527/
#
# Author: Bernhard Bablok, Lothar Hiller (quartz4MHz.asm)
#
# https://github.com/bablokb/pic-toolchain
#
# --------------------------------------------------------------------------

PROJECT=blink_led_quarz4MHz
EXTRA_ASM=quarz4MHz.asm
MODEL=12f675
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------
