# --------------------------------------------------------------------------
# Sample project uart_rxtx
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=uart_rxtx
EXTRA_C=softuart.c
EXTRA_ASM=delay.asm
MODEL=12f675
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------
