# --------------------------------------------------------------------------
# Sample project on_off
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=on_off
MODEL=12f675
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------
