# --------------------------------------------------------------------------
# Sample project blink_led
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=blink_led
ARCH=pic14

PIN_LED=5
SDCC_ARGS=-DPIN_LED=$(PIN_LED)

include ptc_rules.inc

# --------------------------------------------------------------------------
