# --------------------------------------------------------------------------
# Sample project blink_led
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=blink_led
ARCH=pic14

include ../rules.inc

# --------------------------------------------------------------------------

